services:
- type: web
  name: elasticsearch
  env: docker
  plan: starter
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 5
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms128m -Xmx128m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
